### 1. 상품 생성
POST http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlJPTEVfTUFTVEVSIiwiaWF0IjoxNzQ4MTc4NzIxLCJleHAiOjE3NDgxODIzMjF9.zURwQMDKSmcs6mkxanDiFZgTQzSGb63UcFkQdeQ0oXknGvqPES_vBm6ENNcwR1J9AH87sZEK8hzOMvHq2lLqmg
Content-Type: application/json
Accept: application/json


{
  "productName": "새우깡",
  "productPrice": 10000,
  "productQuantity": 200,
  "companyId": "f5844081-d854-438e-96dc-93e272dd9376"
}