spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/babko
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

delivery:
  service:
    url: http://localhost:8088

product:
  service:
    url: http://localhost:8081

company:
  service:
    url: http://localhost:8087