### 1. 정상적인 허브 이동 정보 등록
POST http://localhost:8086/api/v1/hub-movements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicm9sZSI6IlJPTEVfQ09NUEFOWSIsImlhdCI6MTc1Mzc5MzE5NywiZXhwIjoxNzUzNzk2Nzk3fQ.G8IE7SKc8rCQEeQLtlAvr8hQ5E5CLPWX9krs31T-kRf-kXxfPT68Ev0gZ9YPG_zSMp6sq9voT6ELSp9sV-9kOA
Content-Type: application/json
Accept: application/json
X-client-userId: 2
X-client-role: ROLE_MASTER

{
  "departureHubId": "dc7cd20f-abb5-4f5c-9d7f-530d207ad5de",
  "arrivalHubId": "13a1ca90-5a81-4f2e-b426-5b2d05dd5cfd"
}





### 2. 출발 허브가 존재하지 않는 경우
POST http://localhost:8086/api/v1/hub-movements
Content-Type: application/json

{
  "departureHubId": "00000000-0000-0000-0000-000000000000",
  "arrivalHubId": "660f8501-f39c-41d4-a716-556766551111"
}

### 3. 도착 허브가 존재하지 않는 경우
POST http://localhost:8086/api/v1/hub-movements
Content-Type: application/json

{
  "departureHubId": "550e8400-e29b-41d4-a716-446655440000",
  "arrivalHubId": "00000000-0000-0000-0000-000000000000"
}

### 4. 출발 허브와 도착 허브가 동일한 경우
POST http://localhost:8086/api/v1/hub-movements
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "departureHubId": "550e8400-e29b-41d4-a716-446655440000",
  "arrivalHubId": "550e8400-e29b-41d4-a716-446655440000"
}